const INTERVAL_FORMAT = /[0-9]+d,\s[0-9]+h,\s[0-9]+m,\s[0-9]+s/

// provided in seconds
const DEFAULT_PRICE_WATCH_INTERVAL = 300
const DEFAULT_PRICE_WATCH_SINGLE_INTERVAL = 15


module.exports = {
  INTERVAL_FORMAT,
  DEFAULT_PRICE_WATCH_INTERVAL,
  DEFAULT_PRICE_WATCH_SINGLE_INTERVAL,
}
